// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://verxelysubqjqdosyref.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlcnhlbHlzdWJxanFkb3N5cmVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjMxNjQsImV4cCI6MjA1OTkzOTE2NH0.1wtwX-wVnMv1CudeDdqop2oPQNVnYtxeV8S3xDVbqHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);